#!/usr/bin/env bash
# Ensure Nginx is installed
apt-get update -y
apt-get install -y nginx

# 1. Modify nginx.conf to run as 'nginx' user
sed -i 's/^#\s*user\s\+www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/^user\s\+www-data;/user nginx;/g' /etc/nginx/nginx.conf

# 2. Modify default site configuration to listen on port 8080
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:8080 default_server;/g' /etc/nginx/sites-available/default

nginx -t
sudo -u nginx service nginx restart
