#!/usr/bin/env bash

# Check if exactly 4 parameters are provided well
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables for clarity
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# Use scp to transfer the file
# -i: Specifies the path to the private key
# -o StrictHostKeyChecking=no: Disables strict host key checking
# The destination is USERNAME@IP:~/, which transfers the file to the user's home directory
scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
